// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nwqrucovthpgyknaqbwh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im53cXJ1Y292dGhwZ3lrbmFxYndoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODI4Mjk4NzAsImV4cCI6MjA5ODQwNTg3MH0.eDyxQ-IGF6Ez6Y6HO67JAfKjQekPxBTuC8ywm98BiP8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});